VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ImyButton"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Model.Button")
Option Explicit

Public Property Get StartTileX() As Long
End Property

Public Property Get StepTilesX() As Long
End Property

Public Property Get Caption() As String
End Property

Public Property Get Command() As String
End Property

Public Property Get VisibleFor() As String
End Property

Public Property Get StepSize() As Long
End Property

Public Property Get StepsInX() As Long
End Property

