VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ImyFormCond"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
'@Folder("Model.FormCond")
Option Explicit

Public Property Get FBgColor() As Long
End Property

Public Property Get FBgColorTaS() As Double
End Property

Public Property Get FCharColor() As Long
End Property

Public Property Get FCharColorTaS() As Double
End Property

Public Property Get FColumnChar() As String
End Property

Public Property Get FFormula() As String
End Property

Public Property Get FMax() As Long
End Property

Public Property Get FMin() As Long
End Property

Public Property Get FType() As FormattingType
End Property

